---
title: "Testing the Feasibility of Seaweed Cultivation"
output:
  html_document:
    toc: true
    toc_float: true
---
<br>

## Executive Summary

Interest in seaweed aquaculture is growing in CA, but many questions remain as to the feasibility of the industry. To our knowledge, there has been no assessment of the economic feasibility of growing native CA seaweed species for food use. Additionally, no review has been done summarizing which native seaweed species you would grow, how you would grow them, and clearly identified what the limitations and uncertainties regarding seaweed aquaculture in CA. Our project seeks to address these gaps and also provide a framework for future studies to build upon when assessing economic feasibility of seaweed in CA and other regions. Additionally, identifying the most economically promising seaweed species will help direct future research toward these species.


<br>

## Project Objectives

* Identify southern CA candidate seaweed species and the appropriate cultivation methods
* Determine key factors that influence economic feasibility in each species-farm system through the use of a bioeconomic model. 
* Preliminary investigation of incorporating seaweed into an existing mussel farm.

<br>

## Introduction

Seaweed accounts for over a fifth of global annual aquaculture production, at 23.8 million tonnes, and valued at $6.4 billion, with over 95% farmed (FAO, 2014). Out of the 33 countries that harvest seaweed, China is the largest producer by far, followed by Indonesia, with limited production in Western countries. 

<br>

In the international market, the most dominant species are the red seaweeds Kappaphycus alvarezii and Eucheuma spp., which are used to produce carrageenan (FAO, 2014). These are followed by Laminaria japonica (kombu or Japanese kelp), Gracilaria spp., Undaria pinnatifida (wakame) and Porphyra spp. (nori). Porphyra is by far the most valuable seaweed species with two species, P. yezoenisis and P. tenera, constitute the bulk of global production (Jensen, 1993 in Levine and Sahoo, 2009).  

<br>

Over 80% of seaweed is utilized for human consumption through fresh, dried, or processed product while the remainder is used for non-food uses including pharmaceutical, hydrocolloid, and agriculture/aquaculture (West et al., 2016).

<br>

The primary use of seaweed is for human food products, which are either heavily processed (e.g. agar), or served raw (McHugh, 2003). Processed algae, known as algal hydrocolloids are used as emulsifying, gelling or water retention agents. In Asia, seaweeds are used in a broad range of products, however in the West, they are used to produce hydrocolloids (Bixler and Porse, 2010). Numerous health benefits are attributed to seaweed, including high levels of iodine, fiber, vitamin C, and trace minerals, and low fat concentrations, though nutrient contents vary greatly across species (Fleurence, 1999; MacArtain et al., 2007). For example, the calcium concentration in some seaweeds exceeds that of whole milk, making it particularly attractive for use in health food, or vegan products (MacArtain et al., 2007). Given the health benefits associated with consuming seaweed, tremendous potential growth exists for this product in the US, Canada, and Europe in the health conscious markets. 

<br>

The market uses for these species vary, with some used in aquaculture feed, pharmaceuticals, cosmetics, biotechnology, and human consumption (Buckholz et al., 2012). For aquaculture use, seaweeds are typically given directly to consumptive species, such as abalone or sea-cucumber, or processed and added to commercial fish-feeds (Troell et al., 2006; Buckholz et al., 2012). Another rising use of seaweeds is in cosmetics (McHugh, 2003). Seaweed extracts--carrageenan, agar, alginate, and fucodian--are all used as thickening agents, with carrageenan and agar derived from red seaweeds, and alginate and fucoidan are derived from brown seaweed (Bixler and Porse, 2010). Carrageenan is a sulfur polysaccharide extract used as a thickening gel primarily in dairy and meat products; alginate, or sodium alginate, has both food and non-food uses. 

<br>

Over the last few decades, seaweed farming has developed rapidly, since wild harvest was insufficient to meet demand. The seaweed market is growing at a steady rate, doubling between 2000 to 2012 (West et al., 2016). Red seaweeds are growing the most rapidly, at 8% annually (West et al., 2016). Advances in growing strategies and developments of popular seaweed strains have contributed to expansion of this industry. In addition to greater production, the value of seaweed has risen 50% due to rising, still unsatiated, demand (Nayor and Bott, 2014).

<br>

Increasing the use of seaweed in high-end restaurants is an important factor to helping grow the industry, and chefs are increasingly experimenting with seaweed (Mouritsen, 2012). Rapid increase in demand for seaweed products is expected in North America, largely due to the potential for a new, sustainable, healthy protein source (Buck et al., 2016). Thus, the nutritional aspect of seaweed is crucial to potential marketability, but varies greatly between species (McHugh, 2003; MacArtain et al., 2007). Out of the most common species, Pyropia spp. have the highest protein content, and Palmaria palmata the greatest amino acid concentrations (Holdt and Kraan, 2011). Red seaweeds typically contain high protein content, and Gracilaria chilensis was found to have high protein and amino acid concentrations and low lipid concentrations (Ortiz et al., 2009). 

<br>

In the US, both seaweed farming and seaweed imports have grown in the past decades. From 1999 to 2008, seaweed imports increased 65% (InfoFish International, 2011 in Nayor and Bott, 2012). Most seaweed production occurs on the east coast and in Hawai’i, largely through the harvest of Chondrus crispus (irish moss), Palmaria palmata (dulse), more recently, sugar kelp (Saccharina latissima), and Gracilaria spp (ogo or limu). Domestic aquaculture is also increasingly moving towards an ecosystem-based approach known as integrated multi-trophic aquaculture (IMTA), a technique that harnesses the benefits of culturing two or more trophic level species together. 

<br>

Determining the prices, markets, and current production levels of seaweed on the east coast is essential to scoping the potential, and viability, of the west coast market.

<br>

In 2004, total California seaweed harvest amounted to over 33,000 metric tons, making seaweed the 5th most landed species by weight, along the west coast (Norman et al., 2007). As of 2014, harvesting of kelp (Macrocystis pyrifera) had declined rapidly, while edible seaweed harvest (e.g. species from Porphyra, Laminaria, Monostrema and agar bearing plants) increased (CDFW, 2014). Commonly hand harvested seaweed species in California are Macrocystis pyrifera (giant kelp), Nereocystis luetkeana (bull kelp), Mastocarpus papillatus (turkish washcloth), Laminaria setchellii (kombu) and Stephanocystis osmundacea (bladder chain kelp) (CDFW website). The seaweed harvesting hotspots occur in northern California, with the many commercial harvesters operating in Mendocino County and near San Francisco (e.g. Strong Arm Farms in Sonoma, Mendocino Sea Vegetable Company, and Rising Tide Sea Vegetables also in Mendocino). There are strict harvesting regulations, including permitted areas and species, with limits on the annual harvest quantities. 
<br>

While researchers have experimented with seaweed culture in the Atlantic Ocean, businesses are just starting to think about growing seaweed off the coast of California. Suitable local seaweed species, methods for culturing them in the eastern Pacific Ocean, and the economic feasibility of farm methods still need to be identified.

<br> 

Seaweed aquaculture is limited in California, with the only existing production occurring in re-circulating land based tanks. Currently, no ocean farmed seaweed exists in California. The three current seaweed farmers are: Monterey Bay Seaweeds in Moss Landing, Carlsbad Aquafarm in Carlsbad, and The Cultured Abalone Farm in Goleta. The farms in Goleta and Carlsbad grow shellfish, either abalone in tanks or oysters/mussels in the bay, respectively, but both grow Gracilaria pacifica in land-based recirculating tanks. Monterey Bay Seaweed grows Palmaria palmata (Northeast Atlantic dulse), Gracilaria spp. , and Ulva spp. In Goleta, G. pacifica is used for abalone and fish feed, and sold to restaurants and food processors. Monterey Bay Seaweeds sells to chefs and high-end restaurants in the wider Monterey Bay Area (e.g. San Francisco, Santa Cruz), and these seaweeds are processed live, and transported in saline water to the location. The existing seaweed farming market can provide useful insight into both potential seaweed candidates for our client SB Mariculture, and the market to target, along with ideal processing to increase the product’s value. 

<br>

A few seaweed culturists in California use an onshore farm tank system. This can be suitable for species that may fragment, such as G. pacifica (Graham pers. comm), but onshore systems are typically more energy intensive and expensive (Huguenin 1976). “However,  [tank culture in developed countries] has not been adopted on a commercial scale because of the costs involved. The method is very energy intensive because of the need for aeration and large amounts of flowing  seawater.” (FAO Seaweed Culture Guide). Nutrient-rich waters off the U.S. coast provide a unique opportunity to minimize farm inputs, but the industry remains underdeveloped. The open-ocean could be an alternative to land-based systems since few inputs in the form of energy, seawater intake, and nutrients are needed (Nobre et al 2010). Identifying a plot of ocean that is simultaneously suitable habitat for culturing and minimizes ocean user conflicts has been reviewed by Gentry et al 2017. Spatial conflicts are a big obstacle to offshore aquaculture in California (Gentry et al 2017). Much of the space is currently used by the navy, commercial fishing fleets, recreational boaters, and tourism activity. Identifying minimum space requirements and how to alter farm components to produce a profitable offshore farm can help future farmers work around spatial constraints. There are no offshore seaweed farms operating at commercial capacity in the California, and understanding the economic feasibility of growing seaweed in the Santa Barbara Channel could be a good model study for potential farm operations.

<br>

Why local: Environmental benefits and concerns

<br>

In determining the ideal seaweed species to cultivate in the SB channel, the key aspects to consider are biological constraints, market prices and market potential, growth rates, and ease of obtaining seaweed seed.

<br>

## Chapter 1: Identifying Species and Cultivation Methods

Seaweed farming is a multi-stage process that is shaped by the life-history of the cultivated species and greatly influences the cultivation methods taken and their respective costs. Before establishing a seaweed farm, a farmer must decide 1) where to place the farm (onshore or offshore), 2) which species to grow, 3) the best method and timing for cultivating the species, and 4) economic feasibility of these decisions (Titlyanov and Titlayanova, 2010; Radulovich et al., 2015; Figure X). Here we describe the decisions facing a potential seaweed farm and steps that must be taken at the various phases.  

<br>

Location and the species to grow are the first decisions that must be evaluated. For intensive seaweed farming, the two possible locations are onshore or in the ocean (i.e. offshore).  Offshore is used to describe any intensive operation where seaweed is grown in the ocean, regardless of the proximity of the farm to the shore; onshore pertains to seaweed cultivated on-land and includes pond and tank culture. Talk about onshore and offshore cultivation. The different considerations, and the pluses and minuses of each. For offshore, refer to the table. 
Then, move onto the species selection. Why would you select the species you would, and what biological factors influence how you would grow the species you have chosen. 

<br>

Here we talk about vegetative propagation v. reproductive (alternation of generations) in context of specific method (e.g. longline) and timing? Summary of major types (e.g. bottom culture, rope, raft, tank, etc), justification for what we used in Bernard’s farm and in the model for estimating costs/production. In regards to reproductive cultivation: “The principal difficulties in this kind of cultivation lie in the management of the transitions from spore to gametophyte to embryonic sporophyte; these transitions are usually carried out in land-based facilities with careful control of water temperature, nutrients and light” (FAO Fisheries Technical Paper 441, original doc). Broadly, before an individual seaweed reaches harvestable size the following steps must be undertaken: 1) inducing reproduction of parent material leading to the existence of the plantlet (i.e. hatchery phase), 2) settling of the plantlet onto a material for maturation into the adult stage (i.e. nursery phase), and 3) finally the grow-out phase.

<br>

## Chapter 2: Development of Bioeconomic Model

Chapter 1 describes the way in which we collected the relevant growth information from primary literature and experts in phycology. Relative daily growth rate was the main input into our model. It was expressed as a percentage and represented the newly added biomass as a proportion of the previous day’s total. We took  the values presented in literature and evaluated them using empirical farm yields and industry-established harvest frequencies. We elected to use growth rates that most closely matched the expected output of these two factors (TABLE). We chose to examine the model’s sensitivity to yield by running three deterministic scenarios with  low, medium, and high growth rate respectively.  The reproductive nature (vegetative or sexual) and the main abiotic factors that limit growth in each candidate species also played a role in determining the productivity of our model farm systems.


<br>

## Envisioning Co-culture

On the east coast and abroad, aquaculture is increasingly moving towards an ecosystem-based approach known as integrated multi-trophic aquaculture (IMTA), a technique that harnesses the benefits of culturing two or more trophic level species together. Current costs and environmental uncertainty of breeding finfish offshore in the U.S. have led to the creation of an IMTA model growing only shellfish and seaweed, sometimes referred to as co-culture. Encouraging local production of seaweed could lessen our global footprint of importation, but it is just as important to make sure local footprint is minimized. 

<br>

As space can be limited and climate-related risks can impact crop production, many agricultural farms grow multiple crops for economic diversification and spatial efficiency. The economic diversification of co-culture could provide significant benefits in an offshore system that has higher risk than in an onshore farm due to storms, changes in weather. Ocean acidification, or lower pH than expected, can be detrimental for shellfish development due to shifts in pH and carbonate chemistry (Chung, Oak, Lee, Shin, Kim, & Park, 2013). During the springtime, pH tends be lower than usual (source). Commercial operations of shellfish growers in California are frequently monitored for toxins such as domoic acid, which can cause severe illnesses or death after consumption (cdph). When domoic acid dose is detected to be over 20 ug/g, commercial shellfish operations are required to be closed (cdph2). This period is often unpredictable and could last between 3-6 months. During this time, shellfish operations are dormant. Growing a second crop that is not susceptible to domoic acid or ocean acidification can allow the farmer to be more spatially and temporally efficient.

<br>

Based on the rather small number of case histories available the following dose responses can be approximated while recognizing the overlap in ranges and symptoms: 27 to 75 µg/g may result in mild to moderate symptoms (gastrointestinal), 40 to 700 µg/g may result in moderate to severe neurologic symptoms, and domoic acid concentrations greater than 450 µg/g may result in severe neurologic symptoms and/or death (source). Health and Welfare Canada established 20 µg DA/g tissue (20 ppm) above which shellfish commercial operations should be closed. At present, this level has also been adopted by the U.S.31, European Union, New Zealand, and Australia (source). 

<br>

While we have addressed the knowledge gaps of establishing seaweed aquaculture in southern California, permitting and high capital costs are two other important obstacles. Co-culture addresses these two obstacles by reducing the permitting process needed to register for products. 

<br>

Additionally, experiments conducted to answer question of interaction effects between shellfish and seaweed. Give examples of research conducted thus far that gives reason that the interaction is worth investigating. While we weren’t able to 
something about wanting to just see if we can capture any easy observation results in growth of mussels based on these speculations of seaweed helping out shellfish by moderating ocean conditions.

* mussel farm area has more NH4+ (norway paper or something) 
* seaweed absorbs dissolved inorganic nut.
* improving quality of mussels? moderating O2 and pH?
* improved seaweed growth by growing next to animal to produces NH4? (fish-seaweed farm china and other paper shows increased growth - onshore system?, fish effluent has way more NH4 production though)

<br>

Of our candidate species, Gracilaria pacifica was selected for our co-culture investigation. It is the main species that has been cultivated in farm systems in California that also has a niche food market. We know there is already a proof-of-concept for growing G. pacifica onshore and initial growth studies have been conducted for the species in spring. 


<br>


## Concluding Remarks